import React, { useMemo, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { MapPin, Phone, ShoppingCart, Search, Star, Plus, Minus, X, Leaf, Clock, Award, Heart, Send, Menu, Target, Eye, Gem, Sparkles, ChefHat, Navigation, MessageCircle, Flame } from 'lucide-react';
import './styles.css';
import LagunitoAssistant from './LagunitoAssistant.jsx';

const brand = {
  full: 'https://blogger.googleusercontent.com/img/a/AVvXsEgZakzPPpdXiP8lGx-ZT4azhtgPx9tOML4GB45Yc5q-OiuWdkVFxK8lA0gv1eqSSei2weOqr4OpYqwuzmrAYouBkK4MWgXPN_SI7Il3BumyjHI3NzmJyyoAYLYuTzO9ZkvaraaIZaN8TK5TxE2s9rDkEmAHXeVM-PtuSGSsPHpnNmHOj7rcOen43SOOIfE',
  icon: 'https://blogger.googleusercontent.com/img/a/AVvXsEhDw-0oBlrpawZHRqqBTzVEh16xmnQ_AX80O2acX0vnAckJqNRzmGunCxOGqwcbri5Dslhr4c3DSbSb7YvwxB6jzs3TGYWLqk7yixz_wE1j_f36TesK9eefXVXgCrzZ7eRD4rgytl6VjIRyTW62tepO8xKA6P3jvK1EoFUdfUhVeyUFHSnvK0Op08-Ml9c',
  horizontal: 'https://blogger.googleusercontent.com/img/a/AVvXsEg6759--HKCrx3xOaYthRW4dFBWKz35Nfp6CwGdbJ0pXbWz4qdQfnN8C9K0fa0veXINlhG7uM2ro4w3qA4mZ48cHNPOZQ1pOvtEIirKQU3FoKe9d40G3isa79shCQ-C5KtiG8fVqCdLC2FCp6Tw4KcjpYUqErm0MNi8S9KrlKIcQFjFwxCUIYzpcC4V2aE',
};
const heroBackground = 'https://blogger.googleusercontent.com/img/a/AVvXsEioL5ITOpJTxzGC6Go7Jhn6kPCRp1adkZ9wv2ST12waGKqeA7MfzZnelXhTEtfa6QESmniagY85kAbrDDqb-ANTz2PLySZNG35ljd30yPRzhAlF6ydbl_ujtxtXK69AczZK2lBTIyztfJaKFBrrIvQnP2EcN2r7ZqrqsrpfU8i9cXvI_o_lCpTI_SMnpu0';
const orgChartImage = 'https://blogger.googleusercontent.com/img/a/AVvXsEi5GzeLoZmBS_Wt8dLtjPJzSI7B1o9bKE7rvN-95-rENhD1GlOBzyqbK9Y8TtOKBMi51A455VwangnLf9uCBJqr-keXuZ5fC6PtsDHf5KdmAkjXeGNWXVLLEKdcEgc-LA4yjYvCGw6AyMq0oa04oRehLQgbr9VMb3Z5FXPYOFwuk_ZHLTu0h6Zs0njUwg8';
const whatsappNumber = '593999999999';
const mapsUrl = 'https://maps.app.goo.gl/2YEMvyfpp8Y15Euk9';

const products = [
  ['Cheesecake de Maracuyá','Postres',4.99,5.75,4.8,'Cítrico','Postre frío de queso crema con base crocante de galleta y cobertura artesanal de maracuyá. Ideal para quienes buscan un sabor fresco, ácido y dulce al final de la comida.',430,'https://blogger.googleusercontent.com/img/a/AVvXsEgdsEkiZHSXw5gxuD89QrIAcmAPwxqWl8atrVAXTuqjTWCJUPD9oWhy1qFql6zO2uZ5Oz95UlcxlMhCArUwq14sg1lOMBubZ2SYcW9PYojUiZucjYUWbkG_uh_BpjbdG8u92Gx9iuYtjWI5PrJQCQA0SH8ZO8FeKO52jz76Dsm2HSVi413zZkbyJVKgnWs',['Galleta molida','Mantequilla','Queso crema','Leche condensada','Crema de leche','Pulpa de maracuyá']],
  ['Higos con Queso','Postres',6,6.8,4.7,'Tradicional','Postre tradicional de higos cocidos en almíbar de panela, servido con queso fresco. Combina dulzor intenso, aroma de especias y el contraste salado del queso local.',360,'https://blogger.googleusercontent.com/img/a/AVvXsEg5_jpFF5xJf7jI-Al9goNfVxnYO6uDwIvlZUGCNzAQGVXYBrWIKvZKC7hIAxIBQ_R7AKgrT5ebJkPQqkgcmzMPerPwQ-dMqbMlM4hm-j3uVx_KfbWCihlsfEZ6i-ePmAccRQ16YbGbfqbwGzgvua4Wubn2ctOPdR5_lp7XQXMh5aSQlerh_NZHRRfwKpA',['Higos maduros','Panela','Canela','Clavo de olor','Queso fresco','Almíbar artesanal']],
  ['Torta Tres Leches','Postres',3.85,4.5,4.9,'Más pedido','Bizcocho suave de vainilla bañado con mezcla de tres leches, cubierto con crema y toque de canela. Es un postre húmedo, dulce y clásico para compartir.',390,'https://blogger.googleusercontent.com/img/a/AVvXsEhJu97djwIROqKqQca1Y2_6eFUQ--fwqb3yzN21JUUKX5-x74sXJ5xYHgxWU54mud5TddJXwX-btLkg-Xc60SLED1E2qWldObi8E7RXuinvkKx8RWj9k10lTEZQ_wvqi8NiomOWoCSF9B9ZANbP0ua_hpt3vnlTV65veY8dyIfJ3TO4Lf_asF7HFtAE5TQ',['Bizcocho de vainilla','Leche evaporada','Leche condensada','Crema de leche','Merengue','Canela']],
  ['Chicharrón Andino','Entradas',5,5.9,4.8,'Crocante','Trozos de cerdo dorados y crocantes, acompañados con papa, mote, limón, ají de la casa y ensalada fresca de tomate, cebolla y hierbas. Una entrada fuerte con sabor serrano.',720,'https://blogger.googleusercontent.com/img/a/AVvXsEhL-tDaEb4bX39UFT-10vTERC0c13K5IsWM_ktVfmf9PezCY5d6rMF1DzKh3C6JY5dIOo7xWyffnOqCHBJQ_D76Tliu2tk2ikxO8zgAoNk7YMvBMcMC-6ZGIRZns_YBLv0bSDBBAClbgcymfd6aE3MTtFDCCg21Tup0t1ErLBcfywCxuDtouLDm0TA8BgY',['Cerdo seleccionado','Papas doradas','Mote','Ensalada fresca','Ají artesanal','Limón']],
  ['Empanadas de Queso','Entradas',2.7,3.25,4.6,'Familiar','Empanadas de masa dorada y crocante, rellenas con queso fresco local. Se sirven calientes y pueden acompañarse con ají de la casa o una salsa ligera.',310,'https://blogger.googleusercontent.com/img/a/AVvXsEgCB7Ylw37qTOc2a_kkM02R-nHufDIKSpqzP-nem3URuTKq_xsWkmAgKqQGbZKyMcMj_bEovSV2EuE5dOTrD_bQkxIFDVfZNy6dK6UrBPW9sirmRxxmKqX6FKf4Yx3oaDUROB3Ynm4QEz-Q1vHFjXH7hE9Hh-NLiYVTvJdivcsnZPL1wLx6av-cuSSANh4',['Masa artesanal','Queso fresco','Mantequilla','Toque de sal','Aceite vegetal','Ají de la casa']],
  ['Seco de Chivo Tradicional de la Sierra','Platos fuertes',13,15,4.9,'Especialidad','Chivo estofado lentamente con chicha de jora, especias y vegetales. Se acompaña con arroz, plátano maduro, papas y ensalada de cebolla, tomate y cilantro.',950,'https://blogger.googleusercontent.com/img/a/AVvXsEh8ycx6L5gEBIqbgVgv0b-0IjR76-76wjUVjROqfFdk8IFwrrKDY53UYCPxe1t4-YmKe653B9yJkukrhLLhFZrGx5ljJXWDh5OGFR9z1OMrfCv7SWFu_u0J-lsLm5N15UYOz-aJY9M4tUv-Pws5YqUW9QePP5gCEd8icCLeke2mGnpUg7TZFBT0u2gXDno',['Carne de chivo','Chicha de jora','Cebolla','Pimiento','Comino','Arroz','Plátano maduro']],
  ['Cuy Asado al Horno de Leña','Platos fuertes',16.5,18.5,4.8,'Andino','Cuy marinado con ajo, comino y hierbas andinas, asado hasta quedar dorado. Se sirve con papas, mote, salsa de maní y ensalada fresca de la casa.',980,'https://blogger.googleusercontent.com/img/a/AVvXsEgDrLIZ91WmkdLhnlgalGdPmTHm5XmhFhwiSYHmPkG0VFbjShDURqcE-ERWOaejS0j5Y5-lDthlx4RPGLYV0efj_M2n0O5gDUOmt2TRbyM6hAniNs1yW3_TwLGTUqi4aAp5CLX5oyW8su66CUwpisIrLj8IYr1-W-rkYgWavma-ndSX-ne0IWQ3pdRqUgw',['Cuy','Ajo','Comino','Hierbas andinas','Papas','Mote','Salsa de maní']],
  ['Arroz con Pato al Horno','Platos fuertes',15,17,4.7,'Premium','Pato dorado al horno servido sobre arroz meloso preparado con fondo de ave, cilantro, pimiento y arvejas. Incluye guarnición fresca para equilibrar el plato.',870,'https://blogger.googleusercontent.com/img/a/AVvXsEhMQBX3k-3aDfvMb0HEB6K_NRjS0C3ivnrWdF_g9SmUyYBi8UZVP383nCuz5SMenAW7lskGBiFRlvj5Zh0Nnk4wZAAnFtF4iaTM3i9IRnSJ5dt5oZJ-Kg-A1in75haHjAfncH1nvdxi9nhwM4jrOT6LVcsAFzQnZ-fjR3skNYs1y3CA3l-6KJ8FT-elnvE',['Pato','Arroz','Fondo de ave','Cilantro','Pimiento','Arvejas','Especias de la casa']],
  ['Lomo de Cerdo Agridulce','Platos fuertes',9,10.5,4.6,'Creativo','Medallones de cerdo bañados en reducción agridulce de mortiño, acompañados con puré suave, vegetales salteados y ensalada de tomate, cebolla y hojas frescas.',760,'https://blogger.googleusercontent.com/img/a/AVvXsEjQW3EBlUFfdc6gIEOgrxw9p6v40UKzw7ZDlPzx01Z1sFc0O_9DLshWFp1avIZ9aKj7ZSbXScXvN2_OpUPDeTPSYdy1kkGWgW39VpDAMi2xaCOZSi9iX2gtOkYQN_kBhyr5MDIJOSGsA94yEPN4uzxB166sT7dYzthtNQRLIi886u4hM3dOnqkjnPIK6b0',['Lomo de cerdo','Mermelada de mortiño','Miel','Vinagre suave','Zanahoria blanca','Crema','Mantequilla']],
  ['Lomo Saltado de la Villa','Platos fuertes',12,14,4.8,'De la casa','Lomo de res salteado al momento con cebolla morada, tomate, pimiento y ají. Se acompaña con arroz, papas doradas y ensalada fresca de la casa.',890,'https://blogger.googleusercontent.com/img/a/AVvXsEhwBUBIV4GUCwyYFMAZ5HJv1KVUaPDhAruX8z1kAi1or0F0ZISvURl-bqKTZg8BqjDex_z7uQEPCIIS9FGOhzUj0Iu0s1ZPU_I-wNnCK6k6LC4z-nqQ9AETby5IvcVt5xDT0nTwoQuce10OLeqf0l70aVpixVgQjjBlaQRrAKPf3rdF7YqXbD3cES3YBVU',['Lomo de res','Cebolla morada','Pimiento','Tomate','Ají','Arroz','Papas doradas']],
].map(([name, category, price, oldPrice, rating, tag, description, calories, image, ingredients], index) => ({ id: index + 1, name, category, price, oldPrice, rating, tag, description, calories, difference: 'Se diferencia por su preparación cuidadosa, sabor local y presentación cálida de la casa.', images: [image, image], ingredients, features: ['Receta de la casa','Sabor tradicional','Presentación cuidada'] }));

const values = [['Disciplina','Orden, precisión y seguridad alimentaria en cada proceso.'],['Liderazgo','Visión clara para ser referente gastronómico en Cajabamba.'],['Integridad','Ética y transparencia en el servicio, cocina y administración.'],['Armonía','Ambiente cálido desde la llegada hasta el último bocado.'],['Felicidad','La alegría del equipo se transforma en experiencia memorable.'],['Pasión','Cocinar con entusiasmo, identidad local y propósito.'],['Centrado en el cliente','Escuchar, adaptarnos y superar expectativas.']];
const money = (value) => `$${value.toFixed(2)}`;

export default function App() { const [query, setQuery] = useState(''); const [category, setCategory] = useState('Todos'); const [cart, setCart] = useState([]); const [cartOpen, setCartOpen] = useState(false); const [selectedProduct, setSelectedProduct] = useState(null); const [menuOpen, setMenuOpen] = useState(false); const [assistantOpen, setAssistantOpen] = useState(false); const categories = ['Todos', ...new Set(products.map((p) => p.category))]; const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return products.filter((p) => (category === 'Todos' || p.category === category) && `${p.name} ${p.description} ${p.category} ${p.calories} calorias ${p.ingredients.join(' ')}`.toLowerCase().includes(q)); }, [query, category]); const cartCount = cart.reduce((acc, item) => acc + item.quantity, 0); const cartTotal = cart.reduce((acc, item) => acc + item.price * item.quantity, 0); const addToCart = (product) => { setCart((current) => { const found = current.find((item) => item.id === product.id); return found ? current.map((item) => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...current, { ...product, quantity: 1 }]; }); setAssistantOpen(false); setCartOpen(true); }; const changeQuantity = (id, amount) => setCart((current) => current.map((item) => item.id === id ? { ...item, quantity: item.quantity + amount } : item).filter((item) => item.quantity > 0)); const sendOrder = () => { const order = cart.map((item) => `• ${item.name} x${item.quantity} = ${money(item.price * item.quantity)}`).join('%0A'); window.open(`https://wa.me/${whatsappNumber}?text=Hola Villa Laguna, deseo hacer este pedido:%0A%0A${order}%0A%0ATotal: ${money(cartTotal)}`, '_blank'); }; return <div className="site-shell"><Header cartCount={cartCount} onCart={() => setCartOpen(true)} menuOpen={menuOpen} setMenuOpen={setMenuOpen} /><Hero /><BrandStrip /><About /><Values /><Objectives /><Organigram /><Location /><Shop products={filtered} categories={categories} category={category} setCategory={setCategory} query={query} setQuery={setQuery} addToCart={addToCart} setSelectedProduct={setSelectedProduct} /><Footer /><LagunitoAssistant open={assistantOpen} setOpen={setAssistantOpen} cart={cart} cartTotal={cartTotal} /><button className={`floating-cart ${assistantOpen ? 'is-hidden' : ''}`} onClick={() => setCartOpen(true)}><ShoppingCart />{cartCount > 0 && <span>{cartCount}</span>}</button><CartDrawer open={cartOpen} setOpen={setCartOpen} cart={cart} changeQuantity={changeQuantity} total={cartTotal} sendOrder={sendOrder} /><ProductModal product={selectedProduct} onClose={() => setSelectedProduct(null)} onAdd={addToCart} /></div>; }
function Header({ cartCount, onCart, menuOpen, setMenuOpen }) { const links = [['Inicio','#inicio'],['Nosotros','#nosotros'],['Ubicación','#ubicacion'],['Tienda','#tienda']]; return <header className="main-header"><a href="#inicio" className="brand-mark"><img src={brand.horizontal} alt="Villa Laguna Restaurante" /></a><nav className={menuOpen ? 'is-open' : ''}>{links.map(([label, href]) => <a key={label} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav><div className="header-actions"><button className="header-cart" onClick={onCart}><ShoppingCart size={19} /><span>{cartCount}</span></button><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)}><Menu /></button></div></header>; }
function Hero() { return <section id="inicio" className="hero-pro"><div className="hero-media" style={{ backgroundImage: `linear-gradient(90deg, rgba(4,24,24,.96) 0%, rgba(4,24,24,.78) 32%, rgba(4,24,24,.24) 68%), linear-gradient(0deg, rgba(4,24,24,.55), rgba(4,24,24,.02) 48%), url('${heroBackground}')` }} /><motion.div className="hero-panel" initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .75 }}><div className="hero-brand-lockup"><img src={brand.icon} alt="Villa Laguna" /><div><strong>Villa Laguna</strong><span>Restaurante • Cajabamba</span></div></div><p className="micro-label"><Sparkles size={15} /> Restaurante • Cajabamba</p><h1>Sabores tradicionales<br />con vista a la laguna</h1><p>Nos caracterizamos por vender gastronomía tradicional de la localidad de Cajabamba, con platos de identidad serrana, ingredientes frescos y una experiencia cálida frente a la Laguna de Colta.</p><p className="hero-slogan">“La felicidad es el ingrediente secreto de una experiencia memorable.”</p><div className="hero-buttons"><a href="#tienda" className="btn btn-gold"><ShoppingCart size={18} /> Ver tienda</a><a href={mapsUrl} target="_blank" rel="noreferrer" className="btn btn-glass"><Navigation size={18} /> Cómo llegar</a></div></motion.div><div className="hero-card-stack"><div><ChefHat /><strong>Cocina local</strong><span>Recetas de la Sierra con identidad propia.</span></div><div><Leaf /><strong>Ingredientes frescos</strong><span>Productos de la zona y preparación cuidadosa.</span></div><div><Heart /><strong>Servicio cálido</strong><span>Una experiencia pensada para recordar.</span></div></div></section>; }
function BrandStrip(){return <section className="brand-strip"><span>Tradición</span><i/><span>Laguna</span><i/><span>Cajabamba</span><i/><span>Hospitalidad</span></section>}
function About(){return <section id="nosotros" className="section about-premium"><div className="section-heading center"><img src={brand.icon} alt="Símbolo Villa Laguna"/><p className="eyebrow">Nuestra esencia</p><h2>Una villa gastronómica entre paisaje, tradición y calidez</h2><p>Villa Laguna fusiona hospitalidad, frescura natural y orgullo culinario. Celebramos sabores locales con una presentación moderna y un ambiente acogedor.</p></div><div className="manifest-grid mission-vision-only"><InfoCard icon={<Target/>} title="Misión" text="Ofrecemos experiencias gastronómicas auténticas y memorables con ingredientes locales, servicio cálido y ambiente acogedor."/><InfoCard icon={<Eye/>} title="Visión" text="Ser reconocidos para 2030 como restaurante líder en Cajabamba por comida tradicional, innovación y sostenibilidad."/></div></section>}
function Values(){return <section className="section values-premium"><div className="split-layout"><div className="sticky-copy"><p className="eyebrow">Cultura corporativa</p><h2>Valores que se sienten en cada detalle</h2><p>La marca se sostiene en disciplina, pasión y servicio. Cada valor se transforma en una experiencia visible para el cliente.</p></div><div className="value-list">{values.map(([title,text],index)=><motion.article key={title} className="value-row" initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.035}}><Gem size={19}/><div><strong>{title}</strong><span>{text}</span></div></motion.article>)}</div></div></section>}
function Objectives(){return <section className="section objectives-premium"><div className="section-heading center compact"><p className="eyebrow">Objetivos</p><h2>Metas claras para crecer con calidad</h2></div><div className="manifest-grid"><InfoCard icon={<Award/>} title="Rentabilidad" text="Alcanzar utilidad neta del 20% al cierre del primer año y retorno de inversión dentro de 24 meses."/><InfoCard icon={<Clock/>} title="Servicio eficiente" text="Estandarizar procesos para entregar platos en menos de 15 minutos."/><InfoCard icon={<Star/>} title="Calidad digital" text="Lograr una calificación promedio de 4.6/5 en plataformas digitales."/></div></section>}
function Organigram(){return <section className="section org-section only-chart"><div className="org-image-card"><img src={orgChartImage} alt="Organigrama empresarial Villa Laguna"/></div></section>}
function Location(){const galleryItems=['Interior del restaurante','Vista a la laguna','Mesas y ambientación','Cocina y preparación','Fachada','Experiencia de clientes'];return <section id="ubicacion" className="section location-section"><div className="location-grid"><div><p className="eyebrow">Visítanos</p><h2>Ubicación, contacto y experiencia visual</h2><p>Cajabamba – Ecuador. Un espacio pensado para disfrutar comida tradicional, paisajes naturales y atención cercana.</p><div className="contact-actions"><a href={mapsUrl} target="_blank" rel="noreferrer"><MapPin/> Ver ubicación en Google Maps</a><a href={`https://wa.me/${whatsappNumber}`} target="_blank" rel="noreferrer"><Phone/> Pedidos por WhatsApp</a></div></div><div className="restaurant-gallery-card"><div className="gallery-head"><p className="eyebrow">Galería</p><h3>Galería Villa Laguna</h3><span>Conoce nuestros espacios, ambiente y experiencia.</span></div><div className="gallery-preview-grid">{galleryItems.map((item,index)=><article key={item} className="gallery-placeholder"><span>{String(index+1).padStart(2,'0')}</span><strong>{item}</strong></article>)}</div></div></div><div className="review-strip">{['Sabor tradicional con presentación elegante.','Excelente atención y platos abundantes.','Perfecto para comer con vista natural.'].map(r=><article key={r}><span>★★★★★</span><p>{r}</p></article>)}</div></section>}
function Shop({products,categories,category,setCategory,query,setQuery,addToCart,setSelectedProduct}){return <section id="tienda" className="section shop-premium"><div className="section-heading center compact"><p className="eyebrow">Tienda virtual</p><h2>Elige tus platos favoritos y arma tu pedido</h2><p>Busca productos, revisa ingredientes, calorías aproximadas, precios, descuentos y calificaciones.</p></div><div className="shop-tools"><label className="search-box"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar producto, ingrediente o plato..."/></label><div className="filters">{categories.map(item=><button key={item} className={category===item?'active':''} onClick={()=>setCategory(item)}>{item}</button>)}</div></div><div className="product-grid">{products.map(p=><ProductCard key={p.id} product={p} onAdd={addToCart} onDetails={setSelectedProduct}/>)}</div></section>}
function Footer(){return <footer className="footer-pro"><img src={brand.horizontal} alt="Villa Laguna"/><p>Villa Laguna Restaurante • Cajabamba, Ecuador</p><a href={`https://wa.me/${whatsappNumber}`} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Pedir por WhatsApp</a></footer>}
function InfoCard({icon,title,text}){return <motion.article className="info-card" initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><div className="info-icon">{icon}</div><h3>{title}</h3><p>{text}</p></motion.article>}
function ProductCard({product,onAdd,onDetails}){const discount=Math.round((1-product.price/product.oldPrice)*100);return <motion.article className="product-card" whileHover={{y:-8}}><div className="product-photo"><img src={product.images[0]} alt={product.name}/><span className="discount">-{discount}%</span><span className="product-tag">{product.tag}</span></div><div className="product-content"><div className="rating"><Star size={16} fill="currentColor"/> {product.rating}</div><h3>{product.name}</h3><p>{product.description}</p><span className="product-calories"><Flame size={14}/> {product.calories} cal aprox.</span><div className="price-line"><strong>{money(product.price)}</strong><span>{money(product.oldPrice)}</span></div><div className="product-actions"><button onClick={()=>onDetails(product)}>Ver detalles</button><button className="add" onClick={()=>onAdd(product)}><Plus size={18}/> Agregar</button></div></div></motion.article>}
function CartDrawer({open,setOpen,cart,changeQuantity,total,sendOrder}){return <AnimatePresence>{open&&<><motion.div className="overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setOpen(false)}/><motion.aside className="cart-drawer" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}}><div className="drawer-head"><div><p className="eyebrow">Tu pedido</p><h2>Carrito</h2></div><button onClick={()=>setOpen(false)}><X/></button></div>{cart.length===0?<div className="empty-cart"><ShoppingCart size={54}/><h3>Tu carrito está vacío</h3><p>Agrega platos desde la tienda virtual.</p></div>:<><div className="cart-items">{cart.map(item=><div className="cart-item" key={item.id}><img src={item.images[0]} alt={item.name}/><div><h4>{item.name}</h4><span>{money(item.price)}</span><div className="qty"><button onClick={()=>changeQuantity(item.id,-1)}><Minus size={14}/></button><b>{item.quantity}</b><button onClick={()=>changeQuantity(item.id,1)}><Plus size={14}/></button></div></div></div>)}</div><div className="cart-footer"><div><span>Total</span><strong>{money(total)}</strong></div><button className="btn btn-gold full" onClick={sendOrder}><Send size={18}/> Enviar pedido por WhatsApp</button></div></>}</motion.aside></>}</AnimatePresence>}
function ProductModal({product,onClose,onAdd}){return <AnimatePresence>{product&&<><motion.div className="overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose}/><motion.div className="modal" initial={{opacity:0,scale:.94,y:20}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:.94,y:20}}><button className="modal-close" onClick={onClose}><X/></button><div className="modal-gallery"><img src={product.images[0]} alt={product.name}/><img src={product.images[1]} alt={product.name}/></div><div className="modal-body"><p className="eyebrow">{product.category}</p><h2>{product.name}</h2><div className="rating"><Star size={16} fill="currentColor"/> {product.rating} de reputación</div><div className="nutrition-badge"><Flame size={16}/> {product.calories} calorías aprox. por porción</div><p>{product.description}</p><p className="modal-diff"><strong>Diferencial:</strong> {product.difference}</p><div className="modal-detail-grid"><div><h3>Características</h3><div className="chips compact">{product.features.map(f=><span key={f}><Leaf size={13}/> {f}</span>)}</div></div><div><h3>Ingredientes</h3><div className="chips muted compact ingredients-list">{product.ingredients.map(ing=><span key={ing}>{ing}</span>)}</div></div></div><div className="price-line big"><strong>{money(product.price)}</strong><span>{money(product.oldPrice)}</span></div><button className="btn btn-gold full" onClick={()=>onAdd(product)}><Plus size={18}/> Agregar al carrito</button></div></motion.div></>}</AnimatePresence>}
